# Generated by Django 3.1.2 on 2020-11-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Furnitures', 'Furnitures'), ('Footwears', 'Footwears'), ('Clothings', 'Clothings'), ('Accessories', 'Accessories'), ('Home Appliances', 'Home Appliances')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('image', models.URLField()),
                ('category', models.ForeignKey(default='ALL', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product', to='api.category')),
            ],
        ),
    ]
